[phases.build]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements-full.txt"
]

[phases.start]
cmd = "python railway_app.py"

[variables]
FLASK_ENV = "production"
PYTHONPATH = "."