[variables]
PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
PYTHONUNBUFFERED = "1"

[build]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "python railway_app.py"