# railway-simple.toml (Alternative without gunicorn)
[build]
command = "pip install --upgrade pip && pip install -r requirements-full.txt && chmod +x railway-start.sh"

[deploy]
startCommand = "bash railway-start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { FLASK_ENV = "production", PYTHONPATH = ".", DATABASE_URL = "${{DATABASE_URL}}", SECRET_KEY = "${{SECRET_KEY}}", PORT = "${{PORT}}" }