[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python railway_app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[runtime]
python = "3.11"

[variables]
PORT = "5000"
FLASK_ENV = "production"