# railway.toml - Fixed for Railway deployment
[build]
command = "pip install --upgrade pip && pip install -r requirements-full.txt"

[deploy]
startCommand = "python railway_app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { FLASK_ENV = "production", PYTHONPATH = ".", DATABASE_URL = "${{DATABASE_URL}}", SECRET_KEY = "${{SECRET_KEY}}" }