[build]
builder = "NIXPACKS"
nixpacksVersion = "1.21.0"

[deploy]
startCommand = "python railway_app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[runtime]
python = "3.11.0"

[variables]
PORT = "5000"
FLASK_ENV = "production"
PIP_NO_CACHE_DIR = "1"
PYTHONUNBUFFERED = "1"