# railway.toml
[build]
command = "pip install -r requirements-full.txt"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT run:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { FLASK_ENV = "production", PYTHONPATH = ".", DATABASE_URL = "${{DATABASE_URL}}", SECRET_KEY = "${{SECRET_KEY}}" }